### ISSUE TITLE
migration problem after update

### ISSUE THREAD

**Issue by mjtrangoni** [abrt/faf#543]
I made an RPM update yesterday from master branch to our private retrace server, and I am getting some troubles with this. I also discover  'faf-migrate-db' afterwards :-1: 

The question is, how can I get this working again? I click on some Problems reports and the Web-UI is working, but others are not and generate this python crash: 

```
Exception on /reports/124/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/webfaf/reports.py", line 495, in item
    unique_ocurrence_os[os_name]['unique'] += ch.unique
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'NoneType'
```
From `create-problems` I am getting 
```
$ faf create-problems >> /var/log/faf/create-problems.log                                                                                                                    
INFO:faf.CreateProblems:[1 / 5] Processing problem type: Unhandled Python exception
INFO:faf.CreateProblems:Creating problems from clusters
INFO:faf.CreateProblems:[2 / 5] Processing problem type: Kernel oops
INFO:faf.CreateProblems:Creating problems from clusters
INFO:faf.CreateProblems:[3 / 5] Processing problem type: Unhandled Ruby exception
INFO:faf.CreateProblems:No reports found
INFO:faf.CreateProblems:Creating problems from clusters
INFO:faf.CreateProblems:[4 / 5] Processing problem type: Unhandled Java exception
INFO:faf.CreateProblems:No reports found
INFO:faf.CreateProblems:Creating problems from clusters
INFO:faf.CreateProblems:[5 / 5] Processing problem type: Crash of user-space binary
WARNING:faf.CoredumpProblem:Report #549 has only one bad frame
WARNING:faf.CoredumpProblem:Report #416 has only one bad frame
WARNING:faf.CoredumpProblem:Report #419 has only one bad frame
WARNING:faf.CoredumpProblem:Report #623 has only one bad frame
WARNING:faf.CoredumpProblem:Report #634 has only one bad frame
INFO:faf.CreateProblems:Creating problems from clusters
INFO:faf.CreateProblems:Removing empty problems
INFO:faf.CreateProblems:Found 0 empty problems
```

**Comment by jfilak** [comment]
Sorry for the inconvenience. Update your local git repository and retest please. The issue should be fixed.

**Comment by mjtrangoni** [comment]
Hi @jfilak,
`faf-migrate-db` seems to be working now.

```
$ faf-migrate-db --create-all
$ faf-migrate-db --stamp-only
INFO:alembic.runtime.migration:Context impl PostgresqlImpl.
INFO:alembic.runtime.migration:Will assume transactional DDL.
INFO:alembic.runtime.migration:Running stamp_revision 50d3e87e4b2a -> 183a15e52a4f
```

But I still getting this Python crash,

```
Exception on /reports/13/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/webfaf/reports.py", line 495, in item
    unique_ocurrence_os[os_name]['unique'] += ch.unique
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'NoneType'
``` 
It works for some reports but for others, where unique is not defined, it isn't working.
Which script set this unique feld up?

**Comment by patriczek** [comment]
Hi @mjtrangoni 

Yes it's because you are used `faf-migration` with `--stam-only` parameter

`--stamp-only         Don't run any migrations, only stamp the database to indicate it is up-to-date.`

So you didn't make any changes with database structure.

Now you need set head back to 50d3e87e4b2a
`$ psql `
and execute sql command
`UPDATE alembic_version SET version_num = '50d3e87e4b2a';`
then run 
`$ faf-migrate-db --revision head`

I hope this will solve your problem.

**Comment by mjtrangoni** [comment]
Hi @patriczek,

Thanks for your advice, it seems better now. 

```
$ faf-migrate-db --revision head
INFO:alembic.runtime.migration:Context impl PostgresqlImpl.
INFO:alembic.runtime.migration:Will assume transactional DDL.
INFO:alembic.runtime.migration:Running upgrade 50d3e87e4b2a -> 89d35a57f82b, add new value to repo_types enum
INFO:alembic.runtime.migration:Running upgrade 89d35a57f82b -> 13557f1962e6, ureport_added_certainty
INFO:alembic.runtime.migration:Running upgrade 13557f1962e6 -> 17d4911132f8, assigning release to repository
INFO:alembic.runtime.migration:Running upgrade 17d4911132f8 -> 133991a89da4, assign build to operating system, release and architecture
INFO:alembic.runtime.migration:Running upgrade 133991a89da4 -> 183a15e52a4f, Unique column added into report history
```

But I still getting this warning,
```
Exception on /reports/124/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/webfaf/reports.py", line 495, in item
    unique_ocurrence_os[os_name]['unique'] += ch.unique
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'NoneType'
```

Any idea?

**Comment by patriczek** [comment]
@mjtrangoni please try use this commit https://github.com/patriczek/faf/commit/163ebc19a27834ad5f1ccd83e3a71422eb9b8835

Then you need downgrade database to revision `133991a89da4`
`$ cd faf/src/pyfaf/storage/migrations`
`$ alembic downgrade 133991a89da4` 
or in your case you can use
`$ alembic downgrade -1` 
after this you must again upgrade to head
`$ alembic upgrade head`

**Comment by mjtrangoni** [comment]
Thanks @patriczek ! Your commit fixed my issue.
